# Generated by Django 3.2.6 on 2021-08-10 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('en_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('resume', models.JSONField(blank=True, null=True)),
                ('video_id', models.CharField(blank=True, max_length=100)),
                ('categories', models.ManyToManyField(blank=True, related_name='teacher_in_category', to='course.CourseCategoryModel')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
            },
        ),
    ]
