# Generated by Django 3.2.5 on 2021-07-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('resume', models.JSONField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='teacher_in_category', to='course.CategoryModel')),
            ],
        ),
    ]
