# Generated by Django 3.2.5 on 2021-07-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachermodel',
            options={'verbose_name': 'استاد', 'verbose_name_plural': 'اساتید'},
        ),
    ]
