version: '3.3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
