# Generated by Django 3.2.5 on 2021-07-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'موضوع', 'verbose_name_plural': 'موضوعات'},
        ),
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'verbose_name': 'دوره', 'verbose_name_plural': 'دوره\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='coursereviewmodel',
            options={'verbose_name': 'نقد دوره\u200c', 'verbose_name_plural': 'نقد\u200cهای دوره'},
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='discount_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='language',
            field=models.CharField(blank=True, choices=[('fa', 'فارسی'), ('en', 'English')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
