# Generated by Django 3.2.5 on 2021-07-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210704_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('lessons', models.ManyToManyField(related_name='section_of_lesson', to='course.LessonModel')),
            ],
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='sections',
            field=models.ManyToManyField(related_name='course_of_section', to='course.SectionModel'),
        ),
    ]
