# Generated by Django 3.2.5 on 2021-07-19 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_auto_20210719_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereviewlikemodel',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursereviewmodel'),
        ),
        migrations.AlterField(
            model_name='coursereviewlikemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursereviewmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursereviewmodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursemodel'),
        ),
    ]
