# Generated by Django 3.2.5 on 2021-07-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teachermodel_options'),
        ('course', '0003_auto_20210704_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('published', models.BooleanField(default=True)),
                ('lessons', models.ManyToManyField(related_name='section_of_lesson', to='course.CourseLessonModel')),
            ],
        ),
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='CourseCategoryModel',
        ),
        migrations.RemoveField(
            model_name='sectionmodel',
            name='lessons',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursereviewmodel',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='LessonModel',
        ),
        migrations.DeleteModel(
            name='SectionModel',
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='sections',
            field=models.ManyToManyField(related_name='course_of_section', to='course.CourseSectionModel'),
        ),
    ]
