# Generated by Django 3.2.5 on 2021-07-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210705_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselessonmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='courselessonmodel',
            name='video',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='video',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coursesectionmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coursesectionmodel',
            name='video',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
