# Generated by Django 3.2.5 on 2021-07-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210721_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselessonmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coursesectionmodel',
            options={},
        ),
    ]
