# Generated by Django 3.2.5 on 2021-07-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_boughtcoursesmodel_favouritecoursemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='followings_count',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='header',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='trip_status',
        ),
        migrations.AlterField(
            model_name='achievementmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='FollowingModel',
        ),
    ]
