# Generated by Django 3.2.5 on 2021-07-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210721_1210'),
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtcoursesmodel',
            name='complited_lessons',
            field=models.ManyToManyField(related_name='users_comlited', to='course.CourseLessonModel'),
        ),
    ]
