# Generated by Django 3.2.5 on 2021-07-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210721_1210'),
        ('user', '0003_boughtcoursesmodel_complited_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boughtcoursesmodel',
            name='complited_lessons',
        ),
        migrations.AddField(
            model_name='boughtcoursesmodel',
            name='complete_lessons',
            field=models.ManyToManyField(related_name='users_complete', to='course.CourseLessonModel'),
        ),
    ]
