# Generated by Django 3.2.5 on 2021-07-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210721_1210'),
        ('user', '0004_auto_20210721_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtcoursesmodel',
            name='complete_lessons',
            field=models.ManyToManyField(blank=True, related_name='users_completed', to='course.CourseLessonModel'),
        ),
    ]
