# Generated by Django 3.2.5 on 2021-07-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_boughtcoursesmodel_complete_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boughtcoursesmodel',
            name='complete_lessons',
        ),
    ]
