# Generated by Django 3.2.5 on 2021-07-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20210721_1414'),
        ('user', '0006_remove_boughtcoursesmodel_complete_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtcoursesmodel',
            name='complete_lessons',
            field=models.ManyToManyField(blank=True, related_name='users_completed', to='course.CourseLessonModel'),
        ),
    ]
